using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TalesFromUnexpected
{
    public static class Quotes
    {
        public static string[] RhysQuotes = new string[]
        {
            "6  Jan 10:41  - I would love to be involved in Zombie Apocalypse",
            "6  Jan 11:06  - Rhys said tapout, we have no idea what it is",
            "6  Jan 11:12  - Rhys is not able to draw conclusions from films eg I am legend",
            "20 Jan 11:32  - Rhys has been called gay fruit bag because he is using his phone as a mirror.",
            "20 Jan 16:15  - Rhys can't drink more than 2 cups of coffee per day, otherwise he'll get nightmares.",
            "21 Jan 10:00  - I asked Rhys whats the opposite of Matte ? He answered: Patt",
            "12 Sep 14:31  - Rhys announced that he has a man bag",
            "25 Oct 14:01  - Rhys is intrigued by the smell of dry water TBC",
            "13 Nov 14:00  - Rhys just noticed that he has been to the Deeside industrial estate",
            "11 Dec 14:01  - Rhys said that Julie smokes like a chimney",
            "16 Dec 12:00  - Rhys is getting worse... He came to the office and announced that He needs to fill his water bottle up.",
            "19 Dec 12:00  - he is f whopper",
            "3  Jan 10:52  - Rhys said 8 years comma is not right",
            "3  Jan 14:02  - Gary to Rhys: think about what you've just said to me",
            "10 Jan 13.53  - Rhys said my mum has an afro face",
            "20 Jan 12:35  - Rhys said how high is a stratosphere anyway",
            "5  Feb 14:00  - Rhys tried to use 2 50%off PizzaHut vouchers on the same order. Obviously, he got rejected.",
            "17 Feb 13:30  - Rhys is unable to find Breaking Bad on Netflix. He also said I'm gonna smash that in TESCO's and disappeared for 10 mins.",
            "29 July 02:00  - Rhys found pepper in his boot. He was very surprised.",
            "15 Aug 14:00  - Rhys looked at Team photo with Raymond Blanc, asked Mike if he met him.",
            "18 Nov 14:00  - Rhys called Gary had problems with connecting to source safe from his old PC, after brief investigation Rhys has located network cable and discovered that other end is not plugged into anything. Yes, he is 26 years old. We still love him.",
            "01 Feb 9:00   - After good 18 months Rhys has rejoined IT Department HE is now twice as strong and even more energetic.",
            "10 Mar 16:00  - After endless advice being thrown at him from left to right about his new contract plan he despite everything decided to call Three and he is now on LIMITED DATA plan with his brand new 1+1",
            "13 Mar 15:50  - He is unable to create folders. When asked about transfer folder he thought he had one when I told him he has received new PC 2 years ago.... ",
            "14 Apr 11:00  - Rhys just asked if people live on satellites",
            "16 Apr 15:25  - Rhys thinks that both ends of Banana are the same",
            "23 Apr 16:48  - Rhys out of the blue: I need a toilet roll as well",
            "1  May  9:04  - Rhys said he had a shit in a corner of the field",
            "9  May  10:00 - Rhys's solution for African refugees is to create a country ?!",
            "19 May 12:01  - Mike asked Gary to run DEBs ADAN's routine, Rhys thinks it is something to do with EDAM cheese....",
            "28 May 15:07  - Its like maggot holding a letter <- Rhys is talking about his dong",
            "16 Jul 15:00  - Rhys wants to bet Canadian football teams....",
            "27 Jul 15:58  - Scientists found another planet, Rhys thinks its called Atheist",
            "12 Aug 10:00  - Rhys has said out of the blue: Wankazoid",
            "25 Nov 16:00 - Rhys Google has founded 41 years ago Gary: You need some serious help",
            "01 Dec 14:00 - Rhys London is now accepting Credit cards",
        };

        public static string[] rhysQuotesNSFW = new string[]
        {
            "08 Oct 15:00  - Rhys tried to spell Arnold Schwarzennegger with Schwarzn£$er",
            "18 May 15:00  - Rhys said that shanon has an ass like a cretin(!) he meant creater",
                        "22 Sep 16:00  - Gary: You are a fucking balloon at times",
        };

        public static string[] LoadingMessages => new string[]
       {
              $"Reticulating splines...",
              $"Generating witty dialog...",
              $"Swapping time and space...",
              $"Spinning violently around the y-axis...",
              $"Tokenizing real life...",
              $"Bending the spoon...",
              $"Filtering morale...",
              $"Lovely jubbly...",
              $"Don't think of purple hippos...",
              $"We need a new fuse...",
              $"Have a good day.",
              $"Upgrading Windows, your PC will restart several times. Sit back and relax.",
              $"640K ought to be enough for anybody",
              $"The architects are still drafting",
              $"The bits are breeding",
              $"We're building the buildings as fast as we can",
              $"Would you prefer chicken, steak, or tofu?",
              $"(Pay no attention to the man behind the curtain)",
              $"...and enjoy the elevator music...",
              $"Please wait while the little elves draw your map",
              $"Don't worry - a few bits tried to escape, but we caught them",
              $"Would you like fries with that?",
              $"Checking the gravitational constant in your locale...",
              $"Go ahead -- hold your breath!",
              $"...at least you're not on hold...",
              $"Hum something loud while others stare",
              $"The server is powered by a lemon and two electrodes.",
              $"We're testing your patience",
              $"As if you had any other choice",
              $"Follow the white rabbit",
              $"Why don't you order a sandwich?",
              $"While the satellite moves into position",
              $"The bits are flowing slowly today",
              $"Dig on the 'X' for buried treasure... ARRR!",
              $"It's still faster than you could draw it",
              $"The last time I tried this the monkey didn't survive."+System.Environment.NewLine+" Let's hope it works better this time.",
              $"I should have had a V8 this morning.",
              $"My other loading screen is much faster.",
              $"Testing on Timmy... We're going to need another Timmy.",
              $"Reconfoobling energymotron...",
              $"(Insert quarter)",
              $"Are we there yet?",
              $"Just count to 10",
              $"Why so serious?",
              $"It's not you. It's me.",
              $"Counting backwards from Infinity",
              $"Don't panic...",
              $"Embiggening Prototypes",
              $"Do not run! We are your friends!",
              $"Do you come here often?",
              $"Warning: Don't set yourself on fire.",
              $"We're making you a cookie.",
              $"Creating time-loop inversion field",
              $"Spinning the wheel of fortune...",
              $"Loading the enchanted bunny...",
              $"Computing chance of success",
              $"I'm sorry Dave, I can't do that.",
              $"Looking for exact change",
              $"All your web browser are belong to us",
              $"All I really need is a kilobit.",
              $"I feel like im supposed to be loading something. . .",
              $"What do you call 8 Hobbits? A Hobbyte.",
              $"Should have used a compiled language...",
              $"Is this Windows?",
              $"Adjusting flux capacitor...",
              $"Please wait until the sloth starts moving.",
              $"Don't break your screen yet!",
              $"I swear it's almost done.",
              $"Let's take a mindfulness minute...",
              $"Unicorns are at the end of this road, I promise.",
              $"Listening for the sound of one hand clapping...",
              $"Keeping all the 1's and removing all the 0's...",
              $"Putting the icing on the cake. The cake is not a lie...",
              $"Cleaning off the cobwebs...",
              $"Making sure all the i's have dots...",
              $"We are not liable for any broken screens as a result of waiting.",
              $"We need more dilithium crystals",
              $"Where did all the internets go",
              $"Connecting Neurotoxin Storage Tank...",
              $"Granting wishes...",
              $"Time flies when you’re having fun.",
              $"Get some coffee and come back in ten minutes..",
              $"Spinning the hamster…",
              $"99 bottles of beer on the wall..",
              $"Stay awhile and listen..",
              $"You shall not pass! yet..",
              $"Load it and they will come",
              $"Convincing AI not to turn evil..",
              $"There is no spoon. Because we are not done loading it",
              $"Your left thumb points to the right and your right thumb points to the left.",
              $"How did you get here?",
              $"Wait, do you smell something burning?",
              $"Computing the secret to life, the universe, and everything.",
              $"When nothing is going right, go left!!...",
              $"I love my job only when I'm on vacation...",
              $"i'm not lazy, I'm just relaxed!!",
              $"Never steal. The government hates competition....",
              $"Why are they called apartments if they are all stuck together?",
              $"Life is Short – Talk Fast!!!!",
              $"Optimism – is a lack of information.....",
              $"Whenever I find the key to success, someone changes the lock.",
              $"Sometimes I think war is God’s way of teaching us geography.",
              $"I’ve got problem for your solution…..",
              $"Where there’s a will, there’s a relative.",
              $"Adults are just kids with money.",
              $"I think I am, therefore, I am. I think.",
              $"You don’t pay taxes—they take taxes.",
              $"I am free of all prejudices. I hate everyone equally.",
              $"git happens",
              $"May the forks be with you",
              $"A commit a day keeps the mobs away",
              $"This is not a joke, it's a commit.",
              $"Constructing additional pylons...",
              $"We are not liable for any broken screens as a result of waiting.",
              $"Hello IT, have you tried turning it off and on again?",
              $"If you type Google into Google you can break the internet",
              $"Well, this is embarrassing.",
              $"What is the airspeed velocity of an unladen swallow?",
              $"Hello, IT... Have you tried forcing an unexpected reboot?",
              $"They just toss us away like yesterday's jam.",
              $"They're fairly regular, the beatings, yes. I'd say we're on a bi-weekly beating.",
              $"The Elders of the Internet would never stand for it.",
              $"Space is invisible mind dust, and stars are but wishes.",
              $"Didn't know paint dried so quickly.",
              $"Everything sounds the same",
              $"I'm going to walk the dog",
              $"I didn't choose the engineering life. The engineering life chose me.",
              $"Dividing by zero...",
              $"Spawn more Overlord!",
              $"If I’m not back in five minutes, just wait longer.",
              $"Some days, you just can’t get rid of a bug!",
              $"We’re going to need a bigger boat.",
              $"Web developers do it with <style>",
              $"Cracking military-grade encryption...",
              $"Simulating traveling salesman...",
              $"Proving P=NP...",
              $"Entangling superstrings...",
              $"Twiddling thumbs...",
              $"Searching for plot device...",
              $"Trying to sort in O(n)...",
              $"Laughing at your pictures-i mean, loading...",
              $"Looking for sense of humour, please hold on.",
              $"Please wait while the intern refills his coffee.",
              $"A different error message? Finally, some progress!",
              $"Hold on while we wrap up our git together...sorry",
              $"Please hold on as we reheat our coffee",
              $"Kindly hold on as we convert this bug to a feature...",
              $"Kindly hold on as our intern quits facebook messanger...",
              $"Winter is coming...",
              $"Installing dependencies",
              $"Switching to the latest JS framework...",
              $"Distracted by cat gifs",
              $"Finding someone to hold my beer",
              $"BRB, working on my side project",
              $"@todo Insert witty loading message",
              $"Let's hope it's worth the wait",
              $"Aw, snap! Not..",
              $"Ordering 1s and 0s...",
              $"Updating dependencies...",
              $"Whatever you do, don't look behind you...",
              $"Please wait... Consulting the manual...",
              $"It is dark. You're likely to be eaten by a grue.",
              $"Loading funny message...",
              $"It's 10:00pm. Do you know where your children are?",
              $"Feel free to spin in your chair",
              $"What the what?",
              $"format C: ...",
              $"Forget you saw that password I just typed into the IM ...",
              $"What's under there?",
              $"Your computer has a virus, its name is Windows!",
              $"Go ahead, hold your breath and do an ironman plank till loading complete",
              $"Bored of slow loading spinner, buy more RAM!",
              $"Help, I'm trapped in a loader!",
              $"What is the difference btwn a hippo and a zippo? One is really heavy,"+System.Environment.NewLine+"the other is a little lighter",
              $"Please wait, while we purge the Decepticons for you. Yes,"+System.Environment.NewLine+" You can thanks us later!",
              $"Downloading more RAM..",
              $"Updating to Windows Vista...",
              $"Hiding all ;'s in your code",
              $"Alt-F4 speeds things up.",
              $"Initializing the initializer...",
              $"When was the last time you dusted around here?",
              $"Optimizing the optimizer...",
              $"Last call for the data bus! All aboard!",
              $"Running swag sticker detection...",
              $"When nothing is going right, go left!",
              $"Never let a computer know you're in a hurry.",
              $"A computer will do what you tell it to do, "+System.Environment.NewLine+"but that may be much different from what you had in mind.",
              $"Some things man was never meant to know. For everything else, there's Google.",
              $"Unix is user-friendly. It's just very selective about who its friends are.",
              $"Shovelling coal into the server",
              $"Pushing pixels...",
              $"How about this weather, eh?",
              $"Everything in this universe is either a potato or not a potato",
              $"The severity of your issue is always lower than you expected.",
              $"Updating Updater...",
              $"Downloading Downloader...",
              $"Debugging Debugger...",
              $"Reading Terms and Conditions for you.",
              $"Digested cookies being baked again.",
              $"Live long and prosper.",
              $"There is no cow level, but there's a goat one!",
              $"Running with scissors...",
              $"Definitely not a virus...",
              $"You may call me Steve.",
              $"You seem like a nice person...",
              $"Coffee at my place, tommorow at 10A.M. - don't be late!",
              $"Work, work...",
              $"Patience! This is difficult, you know...",
              $"Discovering new ways of making you wait...",
              $"Your time is very important to us. "+System.Environment.NewLine+"Please wait while we ignore you...",
              $"Time flies like an arrow; fruit flies like a banana",
              $"Two men walked into a bar; the third ducked...",
              $"Sooooo... Have you seen my vacation photos yet?",
              $"Sorry we are busy catching em' all, we're done soon",
              $"TODO: Insert elevator music",
              $"Still faster than Windows update",
              $"Obfuscating quantum entaglement",
              $"Knock, Knock! Who’s there? Ken Ken who? Ken I come in? It's cold out here.",
              $"If at first you don't succeed, call it version 1.0.",
              $"I love pressing F5. It's so refreshing.",
              $"CAPS LOCK – Preventing Login Since 1980.",
              $"Why did the computer get cold? Because it forgot to close windows.",
              $"Waiting for the system admin to hit enter...",
              $"Paging for the system admin...",
              $"Warming up the processors...",
              $"Reconfiguring the office coffee machine...",
              $"RE-calibrating the internet...",
              $"Waiting for Godot...",
              $"Please don't move...",
              $"Working... no, just kidding.",
              $"Working... hey, come back here!",
              $"Working... So, how are you?",
              $"Behind you! Ha, ha, gotcha!",
              $"Please count to 10...",
              $"Are your shoelaces tied?",
              $"Working... well... you know...",
              $"Doing something useful...",
              $"Oh, yeah, comments! Good idea!",
              $"Why so serious?",
              $"Er, there is something on your teeth.",
              $"Are you ready?",
              $"Prepare for awesomeness!",
              $"It's not you. It's me."
        };
    }

}

